home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

orders/urls.py
from django.urls import path

from .views import (create_customer, customer_detail, CustomersList,
                    scaffoldig_detail, ScaffoldingList, OrderList, home)

app_name = 'scaffolding'

urlpatterns = [
    path('customers/', CustomersList.as_view(), name='customers_list'),
    path('customers/<int:customer_id>', customer_detail,
         name='customer_detail'),
    path('scaffoldings/', ScaffoldingList.as_view(), name='scaffolds'),
    path('scaffoldings/<int:id>', scaffoldig_detail, name='scaffoldig'),
    path('orders/', OrderList.as_view(), name='orders'),
    path('create/', create_customer, name='create_customer'),
    path('', home, name='home'),
]

page/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'home'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('scaffolding/', include('orders.urls')),
    path('staff/', include('staff.urls')),
]

orders/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Deliver(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='todolist', null=True)
    name = models.CharField(max_length=200)
    code = models.IntegerField()

    def __str__(self) -> str:
        return self.name


class Customer(models.Model):
    customer = models.CharField(max_length=200)
    company_code = models.IntegerField()
    representative = models.CharField(max_length=200)
    adress = models.CharField(max_length=500)
    country = models.CharField(max_length=200)
    email = models.EmailField(blank=True)

    def __str__(self) -> str:
        return self.customer


class Scaffolding(models.Model):
    pastolio_numeris = models.CharField(
        max_length=200, unique=True)
    height = models.IntegerField(default=0)
    width = models.IntegerField(default=0)
    lenght = models.IntegerField(default=0)

    @property
    def volume(self):
        volume = self.height*self.width*self.lenght
        return volume

    def __str__(self) -> str:
        return f'{self.pastolio_numeris}, {self.height}, {self.width}, \
        {self.lenght}, {self.volume}'


class Order(models.Model):
    order = models.CharField(max_length=250, default='')
    deliver = models.ForeignKey(
        Deliver, on_delete=models.CASCADE, default=1)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    scaffoldig = models.ForeignKey(
        Scaffolding, on_delete=models.CASCADE, null=True)
    order_date = models.DateField(default=timezone.now())
    assembled_date = models.DateField(null=True)
    dismanatled_date = models.DateField(null=True)

    Choices = models.TextChoices('Choices', 'Yes No N//A')
    stable = models.CharField(choices=Choices.choices,
                              max_length=50, default='Yes')
    base_leveled = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    number_of_braces = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    platform_guardrails_height = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    gaps_35mm = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    stable_structure = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    proper_sideboards = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    metal_perforated_grating_completely_covers = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    safe_entrance = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    stiff_and_secured = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    tag_filled = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')
    marked_noticed = models.CharField(
        choices=Choices.choices, max_length=50, default='Yes')

    active = models.BooleanField()

    def __str__(self) -> str:
        return self.order

    class Meta:
        ordering = ['order_date']

orders/forms.py
from django import forms


class CreateCustomer(forms.Form):
    company_code = forms.IntegerField(label='Company code:')
    customer = forms.CharField(label='Customer', max_length=200)
    representative = forms.CharField(label='Name/Surname', max_length=200)
    adress = forms.CharField(label='Address', max_length=200)
    country = forms.CharField(label='Coutry', max_length=200)
    email = forms.EmailField(label='Email')


types_of_scaff = ['Standart', 'Hanging', 'Mobile']


class CreateOrder(forms.Form):
    scaffolding_number = forms.CharField(required=False,
                                         label='Scaffolding number:',
                                         max_length=50)
    project_number = forms.IntegerField(label='Project No.', required=False)
    order_number = forms.CharField(label='Order Number', required=False)
    altitude = forms.CharField(label='Altitude', max_length=20, required=False)
    type_of_scaffoldin = forms.CharField(label='Type of scaffolding')

orders/views.py
from django.http import HttpResponseRedirect, Http404
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from .models import Customer, Scaffolding, Order
from .forms import CreateCustomer
from django.urls import reverse


def home(response):
    return render(response, 'orders/base.html', {})
    # return HttpResponse("Testas")


class CustomersList(ListView):
    model = Customer
    template_name = 'orders/customers.html'


class OrderList(ListView):
    model = Order
    template_name = 'orders/orders.html'


def customer_detail(response, customer_id):
    try:
        customer = get_object_or_404(Customer, id=customer_id)
        if response.method == "POST":
            if response.POST.get("save"):
                for order in customer.order_set.all():
                    if response.POST.get("c" + str(order.id)) == "clicked":
                        order.active = True
                    else:
                        order.active = False
                    order.save()
            elif response.POST.get('newOrder'):
                txt = response.POST.get("new")
                if len(txt) > 2:
                    customer.order_set.create(order=txt, active=False)
                else:
                    print("invalid")
    except Customer.DoesNotExist:
        raise Http404

    return render(response, 'orders/customer_detail.html',
                  {"customer": customer})


class ScaffoldingList(ListView):
    model = Scaffolding
    template_name = 'orders/scaffoldings.html'


def scaffoldig_detail(response, id):
    ls = Scaffolding.objects.get(id=id)
    return render(response, 'orders/scaffolding.html', {'ls': ls})


def create_customer(response):
    if response.method == 'POST':
        form = CreateCustomer(response.POST)
        if form.is_valid():
            company_code = form.cleaned_data["company_code"]
            customer = form.cleaned_data["customer"]
            representative = form.cleaned_data["representative"]
            adress = form.cleaned_data["adress"]
            country = form.cleaned_data["country"]
            email = form.cleaned_data["email"]

            t = Customer(company_code=company_code, customer=customer,
                         representative=representative, adress=adress,
                         country=country, email=email)
            t.save()
            return HttpResponseRedirect(reverse('scaffolding:customer_detail',
                                                args=(t.id,)))

    else:
        form = CreateCustomer()
    return render(response, 'orders/create_customer.html', {"form": form})

orders/templates/orders/base.html
<!doctype html>
<html>

<head>
    <style type="text/css">
        .sidenav {
            height: 100%;
            width: 160px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 20px;
        }

        .sidenav a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .main {
            margin-left: 160px;
            padding: 0px 10px;
        }
    </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <title>{% block title%} Hotrema {% endblock %}</title>

</head>

<body>
    <div class="sidenav">
        <a href="{% url 'home:home'%}"> Home </a>
        <a href="{% url 'scaffolding:customers_list'%}"> Customers </a>
        <a href="{% url 'scaffolding:scaffolds'%}"> Scaffoldings </a>
        <a href="{% url 'scaffolding:orders'%}"> Orders </a>
        <a href="{% url 'scaffolding:create_customer'%}"> Create project </a>
    </div>
    <div id='content' , name="content" , class="main">
        <div class="row justify-content-center">
            <div class="col-8">
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>


</html>

orders/templates/orders/create_customer.html
{% extends "orders/base.html" %}
{% block title %} Create new customer {% endblock %}



{% block content %}
<h3>Naujas pirkėjas</h3>
<form method="post" action='/scaffolding/create/' class="form-group">
    {% csrf_token %}
    <div class='input-group mn-3'>
        <div class="input-group-prepend">
            {{form.as_p}}
            <button type='submit' , name='save' class="btn btn-success"> Create </button>
        </div>
    </div>
</form>

{% endblock %}

orders/templates/orders/customer_detail.html
{% extends 'orders/base.html' %}
{% block title %} Customer's projects {% endblock %}

{% block content %}
<h1> {{customer.customer}} </h1>
<form method="post" action="#">
    {% csrf_token %}

    {% for order in customer.order_set.all %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class='input-group-text'>
                {% if order.active == True %}
                <input type="checkbox" , value="clicked" , name="c{{order.id}}" checked>
                {% else %}
                <input type="checkbox" , value="clicked" , name="c{{order.id}}">
                {% endif %}
            </div>
        </div>
        <input type="text" , value="{{order.order}}" class="form-control">
    </div>
    {% endfor %}

    <button type='submit' , name='save' , value='save'>Save</button>>
    <input type="text" , name='new'>
    <button type='submit' , name='newOrder' , value='newOrder'>Add order</button>>
</form>
{% endblock %}

orders/templates/orders/customer_detail1.html
{% extends 'orders/base.html' %}
{% block title %} Customer's projects {% endblock %}

{% block content %}
<h1> {{customer.customer}} </h1>
<form method="post" action="#">
    {% csrf_token %}

    {% for order in customer.order_set.all %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class='input-group-text'>
                {% if order.active == True %}
                <input type="checkbox" , value="clicked" , name="c{{order.id}}" checked>
                {% else %}
                <input type="checkbox" , value="clicked" , name="c{{order.id}}">
                {% endif %}
            </div>
        </div>
        <input type="text" , value="{{order.order}}" class="form-control">
    </div>
    {% endfor %}

    <button type='submit' , name='save' , value='save'>Save</button>>
    <input type="text" , name='new'>
    <button type='submit' , name='newOrder' , value='newOrder'>Add order</button>>
</form>
{% endblock %}

orders/templates/orders/customers.html
{% extends 'orders/base.html' %}

{% block content %}
    
    <h3>Klientų sąrašas</h3>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Company</th>
                <th>Companie's code</th>
                <th>Representative</th>
                <th>Country</th>
            </tr>
        </thead>
        <tbody>
            {% for customer in object_list %}
                <tr>
                    <td>
                       <a href="{% url 'scaffolding:customer_detail' customer.id %}"  > {{ customer.customer}} </a>
                    </td>
                    <td>{{ customer.company_code }}</td>
                    <td>{{ customer.representative }}</td>
                    <td>{{ customer.country }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

orders/templates/orders/orders.html
{% extends 'orders/base.html' %}
{% block title %} Orders {% endblock %}

{% block content %}
<h1> Orders </h1>

<table class='table'>
    <thead>
        <tr>
            <th>Order</th>
            <th>Customer</th>
            <th>Scaffoldig</th>
            <th>Active</th>
        </tr>
    </thead>
    {% for order in object_list %}
    <tbody>
        <tr>
            <th>{{ order.order }}</th>
            <th>{{ order.customer }}</th>
            <th>{{ order.scaffoldig }}</th>
            <th>{{ order.active }}</th>
        </tr>
    </tbody>
    {% endfor %}

</table>
{% endblock %}

orders/templates/orders/scaffolding.html
{% extends 'orders/base.html' %}
{% block title %} Pastoliai {% endblock %}

{% block content %}
<h3> {{ls.height}} </h3> 
<h3> {{ls.volume}} </h3>
<ul>
    {% for item in ls.order_set.all %}
    <li> {{ item.order }}</li>
    {% endfor %}
</ul>
{% endblock %}

orders/templates/orders/scaffoldings.html
{% extends 'orders/base.html' %}
{% block title %} Scaffoldings {% endblock %}

{% block content %}
<h1> Scaffoldings </h1>

<table class='table'>
    <thead>
        <tr>
            <th>Height</th>
            <th>Width</th>
            <th>Lenght</th>
            <th>Volume</th>
        </tr>
    </thead>
    {% for scaffolding in object_list%}
    <tbody>
        <tr>
            <th>{{ scaffolding.height }}</th>
            <th>{{ scaffolding.width }}</th>
            <th>{{ scaffolding.lenght }}</th>
            <th>{{ scaffolding.volume }}</th>
        </tr>
    </tbody>
    {% endfor %}

</table>
{% endblock %}