home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

page/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'home'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('scaffolding/', include('orders.urls')),
    path('staff/', include('staff.urls')),
]

staff/urls.py
from django.urls import path

from .views import (EmployeesList, EmployeesListBonuses,
                    ProjectsList, addEmployee, bonuses, deleteBonus,
                    employeeBonusEdit, employeeDetail, index,
                    project_period, updateBonuses, updateTariff)

app_name = 'staff'


urlpatterns = [
    path('', index, name='index'),

    path('projects/', ProjectsList.as_view(), name='projects_list'),
    path('projects/<int:pk>/month/',
         project_period, name='project_detail'),
    path('projects_date/<int:id>/editTarrif/',
         updateTariff, name="project_tarrif"),
    path('projects_date/<int:pk>/<str:action>/employees/',
         bonuses, name='bonuses'),
    path('projects_date/<int:pk>/addEmployee/',
         addEmployee, name='add_employee'),

    path('projects_date/<int:pk>/updatebonuses/',
         updateBonuses, name='update_bonus'),
    path('projects_date/<int:pk>/deletebonuses/',
         deleteBonus, name='delete_bonus'),

    path('employees/', EmployeesList.as_view(), name='employee_list'),
    path('employees/<int:pk>/', employeeDetail, name='employee_detail'),
    path('employeesBonus/edit/<int:pk>/',
         employeeBonusEdit, name='employee_bonus_edit'),
    path('employeesBonusTotal/', EmployeesListBonuses.as_view(),
         name='employees_bonuses'),
]

staff/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils import timezone


class Project(models.Model):
    project_number = models.CharField(max_length=20, default='', unique=True)
    name = models.CharField(max_length=150, default='')
    country = models.CharField(default="Lietuva", max_length=150)
    started = models.DateField(
        default=timezone.now().today, blank=True, null=True)
    finished = models.DateField(default='', blank=True, null=True)
    created = models.DateField(default=timezone.now)

    class Meta:
        ordering = ['finished', 'started']
        verbose_name_plural = "Objektai"

    def __str__(self) -> str:
        return f'{self.project_number}, {self.name}, {self.country}'


class ProjectDate(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    year_month = models.CharField(
        default='', max_length=7, blank=True, null=True)
    tarrif = models.DecimalField(
        default=0, max_digits=3, decimal_places=2)

    class Meta:
        ordering = ['year_month']
        verbose_name_plural = "Projektai, mėnuo"

    def __str__(self) -> str:
        return f'{self.project}, {self.year_month}, {self.tarrif}'


class Employee(models.Model):
    tabelis = models.IntegerField(default=0)
    name = models.CharField(max_length=120, default='')
    surname = models.CharField(max_length=200, default='')
    kategorija = models.CharField(max_length=100, default='K01')

    class Meta:
        ordering = ['tabelis']
        verbose_name_plural = "Darbuotojai"

    def __str__(self) -> str:
        return f'Nr. {self.tabelis}, {self.name} {self.surname}'

# sita reikia istrinti ir i forma paduoti skirtingus laukus


class EmployeeDate(models.Model):
    employee = models.ForeignKey(Employee, on_delete=CASCADE)
    year_month = models.CharField(
        default='', max_length=7, blank=True, null=True)
    laukas1 = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    laukas2 = models.DecimalField(default=0, max_digits=6, decimal_places=2)

    @property
    def viso(self):
        viso = self.laukas1 + self.laukas2
        return viso

    class Meta:
        ordering = ['employee']
        verbose_name_plural = "Darbuotojo bonusai"

    def __str__(self) -> str:
        return f'Nr. {self.employee}, {self.year_month},\
        {self.laukas1}, {self.laukas2}, {self.viso} '


class Bonus(models.Model):
    project = models.ForeignKey(ProjectDate, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    hours = models.DecimalField(
        default=0, max_digits=5, decimal_places=2)
    priedas_geras_darbas = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)
    apmokymas = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)
    kelione_Lietuva = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)
    kelione_uzsienis = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)
    koordinatoriaus_priedas = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)
    daugiau_nei_12_savaiciu = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)
    klaida_algalapyje = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)
    naujas_darbuotojas = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)
    kita = models.DecimalField(
        default=0, max_digits=6, decimal_places=2)

    @property
    def suma(self):
        suma = self.priedas_geras_darbas + self.apmokymas +\
            self.kelione_Lietuva + self.kelione_uzsienis + \
            self.koordinatoriaus_priedas + self.daugiau_nei_12_savaiciu + \
            self.klaida_algalapyje + self.naujas_darbuotojas + self.kita
        return suma

    class Meta:
        verbose_name_plural = "Lauko bonusai"
        ordering = ['-project']
        unique_together = [['project', 'employee']]

    def __str__(self) -> str:
        return f'{self.employee}, {self.project}, {self.project.year_month}, \
            {self.suma}'

staff/forms.py
from django import forms
from .models import Bonus, ProjectDate, EmployeeDate


class BonusLaikinas(forms.ModelForm):
    laukas1 = forms.DecimalField(
        required=False, widget=forms.TextInput(attrs={'size': '2'}))
    laukas2 = forms.DecimalField(
        required=False, widget=forms.TextInput(attrs={'size': '2'}))

    class Meta:
        model = EmployeeDate
        exclude = ('employee', 'year_month')


class BonusForm(forms.ModelForm):
    hours = forms.DecimalField(widget=forms.TextInput(attrs={'size': '2'}))
    priedas_geras_darbas = forms.DecimalField(
        widget=forms.TextInput(attrs={'size': '2'}))
    apmokymas = forms.DecimalField(
        widget=forms.TextInput(attrs={'size': '2'}))

    class Meta:
        model = Bonus
        fields = '__all__'
        # exclude = ('project',)


class ProjectDateForm(forms.ModelForm):
    class Meta:
        model = ProjectDate
        fields = '__all__'


class EmployeeDateForm(forms.ModelForm):
    class Meta:
        model = EmployeeDate
        fields = '__all__'

staff/views.py
from django.db.models import Q
from django.forms import modelformset_factory, inlineformset_factory
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView
from django.forms import TextInput
from django.contrib.auth.decorators import login_required

from .forms import BonusForm, ProjectDateForm, EmployeeDateForm
from .models import Bonus, Employee, Project, ProjectDate, EmployeeDate
from .own_modules import Period


def laikinas(request):
    bonuses = Bonus.objects.all()
    context = {'bonuses': bonuses}
    return render(request, 'staff/laikinas.html', context=context)


@login_required
def bonuses(request, pk, action='all'):
    project_date = ProjectDate.objects.get(pk=pk)
    bonuses = Bonus.objects.filter(project=pk)

    context = {'bonuses': bonuses, 'action': action,
               'project_date': project_date}

    if action == 'all':
        return render(request, 'staff/bonus_all.html', context=context)
    elif action == 'details':
        return render(request, 'staff/bonus_details.html', context=context)
    elif action == 'edit':
        dydis = {'size': '3'}
        widgets = {
            'hours': TextInput(attrs=dydis),
            'priedas_geras_darbas': TextInput(attrs=dydis),
            'apmokymas': TextInput(attrs=dydis),
            'kelione_Lietuva': TextInput(attrs=dydis),
            'kelione_uzsienis': TextInput(attrs=dydis),
            'koordinatoriaus_priedas': TextInput(attrs=dydis),
            'daugiau_nei_12_savaiciu': TextInput(attrs=dydis),
            'klaida_algalapyje': TextInput(attrs=dydis),
            'naujas_darbuotojas': TextInput(attrs=dydis),
            'kita': TextInput(attrs=dydis),
        }
        BonusFormSet = modelformset_factory(
            Bonus, fields='__all__', exclude=('project',),
            widgets=widgets, extra=0)

        if request.method == "POST":
            formset = BonusFormSet(
                request.POST, request.FILES, queryset=bonuses)
            if formset.is_valid():
                formset.save()
                return HttpResponseRedirect(reverse('staff:bonuses',
                                                    args=(pk, 'all')))
            else:
                print(formset.errors)
        else:
            formset = BonusFormSet(queryset=bonuses)

        context['formset'] = formset
        return render(request, 'staff/bonus_edit.html', context=context)


# @login_required
class ProjectsList(ListView):
    model = Project
    template_name = 'staff/projects.html'
    context_object_name = 'projects'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            query = self.request.GET.get('q')
            object_list = Project.objects.filter(Q(name__icontains=query))
            return object_list
        else:
            return Project.objects.all()


@login_required
def updateTariff(request, id):
    projectDate = ProjectDate.objects.get(id=id)
    form = ProjectDateForm(instance=projectDate)
    if request.method == 'POST':
        form = ProjectDateForm(request.POST, instance=projectDate)
        if form.is_valid():
            form.save()

            bonuses = Bonus.objects.filter(project=id)
            for b in bonuses:
                b.priedas_geras_darbas = b.hours * b.project.tarrif
                b.save()

            return HttpResponseRedirect(reverse('staff:project_detail',
                                                args=(projectDate.project.id,)
                                                )
                                        )
        else:
            form = ProjectDateForm(instance=projectDate)

    context = {"form": form}
    return render(request, 'staff/updateTarrif.html', context=context)


@login_required
def project_period(request, pk, edit=None):
    try:
        project = get_object_or_404(Project, id=pk)
        period = Period()
        project_date = ProjectDate.objects.filter(project=pk)

        three_months = [period.two_months_ago,
                        period.last_month, period.current_month]
        tarrifs = []
        project_date_id = []
        for month in three_months:
            try:
                tarrifs.append(project_date.filter(year_month=month)[0])
            except IndexError:
                proj = ProjectDate(
                    project=project, year_month=month, tarrif=0)
                proj.save()
                project_date_id.append(proj.id)
                tarrifs.append(proj)

        context = {'project': project, 'project_date': project_date}

        return render(request, 'staff/project.html', context=context)
    except Project.DoesNotExist:
        raise Http404


@login_required
def addEmployee(request, pk):
    BonusFormSet = inlineformset_factory(ProjectDate, Bonus, fields=[
                                         'employee', 'hours',
                                         'priedas_geras_darbas', 'apmokymas',
                                         'kelione_Lietuva', 'kelione_uzsienis',
                                         'koordinatoriaus_priedas',
                                         'daugiau_nei_12_savaiciu',
                                         'klaida_algalapyje',
                                         'naujas_darbuotojas',
                                         'kita'], extra=1)
    project_date = ProjectDate.objects.get(id=pk, )
    formset = BonusFormSet(queryset=Bonus.objects.none(),
                           instance=project_date)
    if request.method == "POST":
        formset = BonusFormSet(request.POST, instance=project_date)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(reverse('staff:bonuses',
                                                args=(project_date.id,
                                                      'all')))
        else:
            formset = BonusFormSet(queryset=Bonus.objects.none(),
                                   instance=project_date)
    context = {'formset': formset, 'project_date': project_date}

    return render(request, 'staff/addEmployee.html', context=context)


@login_required
def updateBonuses(request, pk):
    bonus = Bonus.objects.get(id=pk)
    form = BonusForm(instance=bonus)
    if request.method == 'POST':
        form = BonusForm(request.POST, instance=bonus)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('staff:bonuses',
                                                args=(bonus.project.id,
                                                      'all')))
        else:
            form = BonusForm(instance=bonus)

    context = {"form": form, 'action': 'all'}
    return render(request, 'staff/addEmployee.html', context=context)


@login_required
def deleteBonus(request, pk):
    bonus = Bonus.objects.get(id=pk)
    if request.method == "POST":
        bonus.delete()
        return HttpResponseRedirect(reverse('staff:bonuses',
                                            args=(bonus.project.id, 'all')))
    context = {"bonus": bonus, 'action': 'all'}
    return render(request, 'staff/deleteBonuses.html', context=context)


@login_required
def index(request):
    return render(request, 'staff/base.html', {})


# @login_required
class EmployeesList(ListView):
    model = Employee
    template_name = 'staff/employees.html'
    context_object_name = 'employees'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            query = self.request.GET.get('q')
            object_list = Employee.objects.filter(
                Q(name__icontains=query) | Q(
                    surname__icontains=query) | Q(tabelis__icontains=query)
            )
            return object_list
        else:
            return Employee.objects.all()

    def post(self, request):
        Employee.object.create()


@login_required
def employeeDetail(request, pk):
    employee = Employee.objects.get(id=pk)
    employee_month = EmployeeDate.objects.filter(employee=pk)
    context = {"employee_months": employee_month, 'employee': employee}
    return render(request, 'staff/employee.html', context=context)


@login_required
def employeeBonusEdit(request, pk):
    employeeDate = EmployeeDate.objects.get(id=pk)
    form = EmployeeDateForm(instance=employeeDate)
    context = {'employeeDate': employeeDate, 'form': form}
    if request.method == 'POST':
        form = EmployeeDateForm(request.POST, instance=employeeDate)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('staff:employee_detail',
                                                args=(
                                                    employeeDate.employee.id,)
                                                ))
        else:
            form = EmployeeDateForm(instance=employeeDate)

    return render(request, 'staff/employeeEdit.html', context=context)


class EmployeesListBonuses(ListView):
    model = Employee
    template_name = 'staff/employeesBonuses.html'
    context_object_name = 'employees'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            query = self.request.GET.get('q')
            object_list = Employee.objects.filter(
                Q(name__icontains=query) | Q(
                    surname__icontains=query) | Q(tabelis__icontains=query)
            )
            return object_list
        else:
            return Employee.objects.all()

staff/templates/staff/addEmployee.html
{% extends 'staff/base.html' %}


{% block content %}

<h4> {{project_date.project}}, {{project_date.year_month}} </h4>

<div class="row">
    <div class="col-md-8">
        <div class="card card-body">

            <form action="" method="post">
                {% csrf_token %}
                {{ formset.management_form}}
                {% for form in formset %}
                    {{ form.as_ul }}
                    <hr>
                {% endfor %}
                <input type="submit" value="Tvirtinti">
            </form>
        </div>
    </div>
</div>

{% endblock  %}

staff/templates/staff/base.html
<!doctype html>
<html>

<head>
<style type="text/css">
        .sidenav {
            height: 100%;
            width: 160px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 20px;
        }

        .sidenav a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        
        .main {
            margin-left: -5px;
            padding: 0px 0px;
        }
    </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <title>{% block title%} HOTREMA {% endblock %}</title>

</head>

<body>
    <div class="sidenav">
        <a href="{% url 'home:home' %}"> Home </a>
        <a href="{% url 'staff:projects_list' %}"> Projektų vadovai </a>
        <a href="{% url 'staff:employee_list' %}"> Finansai </a>
        <a href="{% url 'staff:employees_bonuses' %}"> Viso </a>
    </div>
    <div id='content' , name="content" , class="main">
        <div class="row justify-content-center">
            <div class="col-8">
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>


</html>

staff/templates/staff/bonus_all.html
{% extends 'staff/base.html' %}

{% block content %}

<div class="col-md-7" >
    <h4>Projektas: Nr. {{project_date.project.project_number}}, {{project_date.project.name}}</h4>
    <h5>Laikotarpis {{project_date.year_month}}</h5>
    
    <a class="btn btn-primary"
    href="{% url 'staff:bonuses' pk=project_date.id action='all'%}" 
    role="button">Viso</a>
    <a class="btn btn-secondary" 
    href="{% url 'staff:bonuses' pk=project_date.id action='details'%}"
    role="button">Detaliau</a>
    <a class="btn btn-secondary" 
    href="{% url 'staff:bonuses' pk=project_date.id action='edit'%}"
    role="button">Redaguoti</a>

    <a class="btn btn-dark" 
    href="{% url "staff:add_employee" pk=project_date.id %}"
    role="button">Naujas darbuotojas</a>
    </div>

    <div class="card card-body" style="width:85%">
        
        <table class="table table-sm">
            <tr>
                <th></th>
                <th></th> 
                <th>Darbuotojas</th>
                <th>Priedas</th>
            </tr>
            {% for bonus in bonuses %}
                <tr>
                    {% include "staff/button_update_detele.html" %}
                    <td> {{bonus.employee}} </td>
                    <td> {{bonus.suma}} </td>
                </tr>
             
            {% endfor %}
        </table>


</div>


{% endblock %}

staff/templates/staff/bonus_create.html
{% extends 'staff/base.html' %}

{% block content %}

<h3> Ivedimo forma </h3>

<form action="{% url 'staff:bonusescreate' %}" method="post">
    {% csrf_token %}
    {{ form.name_of_field }}
    <table class="table table-bordered table-hover" style="width:70%">
        <thead>
            <tr>               
                <th>Darbuotojas</th>
                <th>Geras darbas</th>
                <th>Lauko priedas</th>
                <th>Apmokymas</th>
                <th>Vairavimas į vieną pusę dviese</th>
                <th>Vairavimas į vieną pusę vienas</th>
                <th>Vairavimas Lietuvoje</th>
                <th>Važiavimas Lietuvoje</th>
                <th>Stažas</th>
                <th>Koordinatoriaus priedas</th>
                <th>Daugiau nei 12 savaičių</th>
                <th>Klaida algalapyje</th>
                <th>Naujas darbuotojas</th>
                <th>Kita</th>
            </tr>
        </thead>
        {% for employee in employees %}
        <tbody>
                <tr>
                    <td>{{ employee.employee }}</td>
                    <td>{{ form.priedas_geras_darbas }}</td>
                    <td>{{ form.lauko_priedas }}</td>
                    <td>{{ form.apmokymas }}</td> 
                    <td>{{ form.vair_i_viena_puse_dviese }}</td>
                    <td>{{ form.vair_i_viena_puse_vienas }}</td>
                    <td>{{ form.vair_lietuvoje }}</td>
                    <td>{{ form.vaziavimas_lietuvoje }}</td>
                    <td>{{ form.stazas }}</td>
                    <td>{{ form.koordinatoriaus_priedas }}</td>
                    <td>{{ form.daugiau_nei_12_savaiciu }}</td>
                    <td>{{ form.klaida_algalapyje }}</td>
                    <td>{{ form.naujas_darbuotojas }}</td>
                    <td>{{ form.kita }}</td>
                </tr>
        </tbody>
        {% endfor %}
    </table>
    <input type="submit" value="Tvirtinti">
</form>


{% endblock %}

staff/templates/staff/bonus_details.html
{% extends 'staff/base.html' %}

{% block content %}

<style>
th {
  background-color:tomato;
  border: 2px solid powderblue;
  padding: 30px;
  font-size:80%;
  text-align:center;
}

td {
  background-color:tomato;
  border: 2px solid powderblue;
  padding: 30px;
  font-size:80%;
  text-align:center;
}

</style>

<div class="col-md-7">
    <h4>Projektas: Nr. {{project_date.project.project_number}}, {{project_date.project.name}}</h4>
    <h5>Laikotarpis {{project_date.year_month}}</h5>
    <a class="btn btn-secondary"
    href="{% url 'staff:bonuses' pk=project_date.id action='all'%}" 
    role="button">Viso</a>
    <a class="btn btn-primary" 
    href="{% url 'staff:bonuses' pk=project_date.id action='details'%}"
    role="button">Detaliau</a>
    <a class="btn btn-secondary" 
    href="{% url 'staff:bonuses' pk=project_date.id action='edit'%}"
    role="button">Redaguoti</a>
    <a class="btn btn-dark" 

    <a class="btn btn-dark" 
    href="{% url "staff:add_employee" pk=project_date.id %}"
    role="button">Naujas darbuotojas</a>
        
    <table class="table table-sm" style="width:85%" >
        <tr>
            <th></th>
            <th></th>
            <th>Darbuotojas</th>
            <th>Valandos</th>
            <th>Priedas geras darbas</th>
            <th>Apmokymas</th>
            <th>Kelionė Lietuvoje</th>
            <th>Kelionė užsienyje</th>
            <th>Koordinatoriaus priedas</th>
            <th>>12 savaičių</th>
            <th>Klaida algalapyje</th>
            <th>Naujas darbuotojas</th>
            <th>Kita</th>
            <th>Viso</th>
        </tr>
        {% for bonus in bonuses %}
            <tr>
                {% include "staff/button_update_detele.html" %}    
                <td> {{bonus.employee}} </td>
                <td>{{ bonus.hours }}</td>
                <td>{{ bonus.priedas_geras_darbas }}</td>
                <td>{{ bonus.apmokymas }}</td>
                <td>{{ bonus.kelione_Lietuva }}</td>
                <td>{{ bonus.kelione_uzsienis }}</td>
                <td>{{ bonus.koordinatoriaus_priedas }}</td>
                <td>{{ bonus.daugiau_nei_12_savaiciu }}</td>
                <td>{{ bonus.klaida_algalapyje }}</td>
                <td>{{ bonus.naujas_darbuotojas }}</td>
                <td>{{ bonus.kita }}</td>
                <td>{{ bonus.suma }}</td>
            </tr>
            
        {% endfor %}
    </table>

</div>


{% endblock %}

<div class='row'>

staff/templates/staff/button_update_detele.html
<td><a class='btn btn-sm btn-info' 
href="{% url 'staff:update_bonus' pk=bonus.id %}"
>Update</a>
</td>
<td><a class='btn btn-sm btn-danger' 
href="{% url 'staff:delete_bonus' pk=bonus.id %}"
>Delete</a></td>

staff/templates/staff/employee.html
{% extends 'staff/base.html' %}


{% block content %}

    <h4> {{employee.name}} {{employee.surname}}</h4>
    <table class="table table-bordered table-hover">
    <thead>
            <tr>
                <th> Mėnuo </th>
                <th> Viso </th>
                <th> Laukas1 </th>
                <th> Laukas2 </th>
                <th>  </th>
            </tr>
            {% for emp in employee_months %}
            <tr>
            <th> {{emp.year_month}} </th>
            <th> {{emp.viso}} </th>
            <th> {{emp.laukas1}} </th>
            <th> {{emp.laukas2}} </th>
            <th><a class="btn btn-primary" 
                    href="{% url 'staff:employee_bonus_edit' pk=emp.id %}"
                    role="button">Redaguoti</a></th>
            </tr>
            {% endfor %}
        </thead>

    </table>

{% endblock %}

staff/templates/staff/employeeEdit.html
{% extends 'staff/base.html' %}

{% block content %}

    <h4> {{employee.name}} {{employee.surname}}</h4>
    <h3> Bonusų suvedimas </h3>

    <div class="row">
        <div class="col-md-8">
            <div class="card card-body">

                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_ul }}
                    <input type="submit" value="Tvirtinti">
                </form>
            </div>
        </div>
    </div>

{% endblock  %}

staff/templates/staff/employees.html
{% extends 'staff/base.html' %}

{% block content %}

    <h3>Darbuotojų sąrašas</h3>

    <p1><i> Paspauskite ant tabelio.</i></p1>

    <form action="{% url 'staff:employee_list' %}" method="get">
        <input name="q" type="text" placeholder="Ieškome...">
    </form>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>               
                <th>Vardas</th>
                <th>Pavardė</th>
                <th>Tabelio numeris</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
                <tr>
                    <td>{{ employee.name }}</td>
                    <td>{{ employee.surname }}</td>
                    <td>
                       <a href="{% url 'staff:employee_detail' pk=employee.id %}"  > {{ employee.tabelis}} </a>
                    </td>
                    
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock  %}

staff/templates/staff/projects.html
{% extends 'staff/base.html' %}


{% block content %}
    
    <h3>Projektų sąrašas</h3>

    <form action="{% url 'staff:projects_list' %}" method="get">
    <input name="q" type="text" placeholder="Ieškome...">
    </form>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Kodas</th>
                <th>Projektas</th>
                <th>Šalis</th>
                <th>Pradžia</th>
                <th>Pabaiga</th>
                <th>Projektas sukurtas</th>
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
                <tr>
                    <td>{{ project.project_number }}</td>
                    <td>
                       <a href="{% url 'staff:project_detail' project.id %}"  > {{ project.name}} </a>
                    </td>
                    <td>{{ project.country }}</td>
                    {% if project.started == None %}
                        <td> </td>
                    {% else %}
                        <td>{{ project.started }}</td>
                    {% endif %}
                    {% if project.finished == None %}
                        <td> </td>
                    {% else %}
                        <td>{{ project.finished }}</td>
                    {% endif %}

                    <td>{{ project.created }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}